from fpdf import FPDF
import datetime

class GrantPDF(FPDF):
    def header(self):
        # Logo or Title
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Grant Seeker AI - Opportunity Summary', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by Grant Seeker AI on {datetime.date.today()}', 0, 0, 'C')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(230, 240, 255)  # Light blue background
        self.cell(0, 8, f"{label}", 0, 1, 'L', 1)
        self.ln(2)

    def chapter_body(self, text):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 6, f"{text}")
        self.ln(4)

def sanitize_text(text: str) -> str:
    """
    Sanitize text to be compatible with Latin-1 encoding for FPDF.
    Replaces common smart characters with ASCII equivalents and strips others.
    """
    if not text:
        return ""
    
    # Replace common smart characters
    replacements = {
        '\u2018': "'", '\u2019': "'",  # Smart quotes
        '\u201c': '"', '\u201d': '"',  # Smart double quotes
        '\u2013': '-', '\u2014': '-',  # Dashes
        '\u2026': '...',               # Ellipsis
        '\u00a0': ' ',                 # Non-breaking space
        '\u2022': '*',                 # Bullet
    }
    
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
        
    # Final safety net: Force encode to ascii/latin-1 with replacement
    return text.encode('latin-1', 'replace').decode('latin-1')

def generate_grant_pdf(grant_data: dict) -> bytes:
    """
    Generates a PDF byte stream for the given grant data.
    """
    pdf = GrantPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Title and Funder
    pdf.set_font('Arial', 'B', 16)
    title = sanitize_text(grant_data.get('title', 'Untitled Grant'))
    pdf.multi_cell(0, 8, title, align='C')
    pdf.ln(2)
    
    pdf.set_font('Arial', 'I', 12)
    funder = sanitize_text(f"Funder: {grant_data.get('funder', 'Unknown Funder')}")
    pdf.cell(0, 8, funder, 0, 1, 'C')
    pdf.ln(8)
    
    # Key Details Table-like structure
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(40, 8, "Deadline:", 0, 0)
    pdf.set_font('Arial', '', 11)
    deadline = sanitize_text(grant_data.get('deadline', 'N/A'))
    pdf.cell(0, 8, deadline, 0, 1)
    
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(40, 8, "Amount:", 0, 0)
    pdf.set_font('Arial', '', 11)
    amount = sanitize_text(grant_data.get('amount', 'N/A'))
    pdf.cell(0, 8, amount, 0, 1)
    
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(40, 8, "Location:", 0, 0)
    pdf.set_font('Arial', '', 11)
    geography = sanitize_text(grant_data.get('geography', 'N/A'))
    pdf.cell(0, 8, geography, 0, 1)
    
    pdf.ln(6)
    
    # Description
    pdf.chapter_title("Description")
    description = grant_data.get('description') or grant_data.get('detailed_overview') or "No description provided."
    pdf.chapter_body(sanitize_text(description))
    
    # Eligibility
    pdf.chapter_title("Eligibility")
    eligibility = grant_data.get('eligibility', 'Not specified')
    pdf.chapter_body(sanitize_text(eligibility))
    
    # Requirements
    pdf.chapter_title("Application Requirements")
    reqs = grant_data.get('application_requirements', [])
    if isinstance(reqs, list) and reqs:
        req_text = "\n".join([f"- {r}" for r in reqs])
    elif isinstance(reqs, str):
        req_text = reqs
    else:
        req_text = "Not specified"
    pdf.chapter_body(sanitize_text(req_text))
    
    # Link
    pdf.ln(4)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 8, "Official Link:", 0, 1)
    pdf.set_font('Arial', 'U', 11)
    pdf.set_text_color(0, 0, 255)
    url = sanitize_text(grant_data.get('url', ''))
    if url:
        pdf.write(5, url, url)
    else:
        pdf.write(5, "No URL provided")
    
    # Return bytes - Use error handling for final encoding
    return pdf.output(dest='S').encode('latin-1', errors='replace')
